#############################################################################
# Makefile for building: neurondyn
# Generated by qmake (2.01a) (Qt 4.7.3) on: Sat Feb 11 12:34:49 2012
# Project:  neurondyn.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile neurondyn.pro
#############################################################################

####### Compiler, tools and options

CC            = $(CCACHE) /Developer/usr/bin/llvm-gcc-4.2
CXX           = $(CCACHE) /Developer/usr/bin/llvm-g++-4.2
DEFINES       = 
CFLAGS        = -pipe -O2 $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-g++ -I. -I. -Isrc -I/opt/local/include/eigen2 -I/usr/include/eigen2 -I/opt/local/include -I/opt/local/include/QtGui -I/opt/local/include/QtCore -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui
LINK          = $(CCACHE) /Developer/usr/bin/llvm-g++-4.2
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS)   -L/opt/local/lib -lgsl -lgslcblas -fopenmp -lconfig++ -lQtGui -lQtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cc \
		src/netdyn.cc 
OBJECTS       = main.o \
		netdyn.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/mac-g++.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		neurondyn.pro
QMAKE_TARGET  = neurondyn
DESTDIR       = 
TARGET        = neurondyn

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: neurondyn.pro  /opt/local/share/qt4/mkspecs/macx-g++/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/mac-g++.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf
	$(QMAKE) -o Makefile neurondyn.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/mac-g++.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile neurondyn.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/neurondyn1.0.0 || $(MKDIR) .tmp/neurondyn1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/neurondyn1.0.0/ && (cd `dirname .tmp/neurondyn1.0.0` && $(TAR) neurondyn1.0.0.tar neurondyn1.0.0 && $(COMPRESS) neurondyn1.0.0.tar) && $(MOVE) `dirname .tmp/neurondyn1.0.0`/neurondyn1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/neurondyn1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_clean: 

####### Compile

main.o: src/main.cc src/main.h \
		src/netdyn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cc

netdyn.o: src/netdyn.cc src/netdyn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netdyn.o src/netdyn.cc

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

